config/routes.rb
Rails.application.routes.draw do
  root to: "pages#home"

  get 'bikes/index'
  # get 'bikes/new'

  devise_for :users

  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  get '/account', to: 'pages#account'

  get '/bookings', to: 'bookings#index'

  get '/near_me', to: 'bikes#near_me'
  get '/filter', to: 'bikes#filter'

  # Defines the root path route ("/")
  # root "articles#index"
  patch "bikes/:id/changes", to: "bikes#change", as: "change"
  
  resources :bikes, only: %i[index new create show update edit filter] do
    resources :bookings, only: %i[new create]
  end

  # resources :pages


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/bike.rb
class Bike < ApplicationRecord
  belongs_to :user
  has_many :bookings
  has_many :users, through: :bookings
  geocoded_by :location
  after_validation :geocode, if: :will_save_change_to_location?

  has_one_attached :photo
  # to be added to the form  <%= f.input :photo, as: :file %>
    # def article_params
      # params.require(:article).permit(:title, :body, :photo)
    # end

  CATEGORIES = ['City bike', 'Road bike', 'BMX bike', 'Cargo bike', 'Mountain bike', 'Fixie bike']
  GEARS = ['No gears', '3', '7', '18', '21', '28']

  validates :name, presence: true
  validates :bike_type, presence: true, inclusion: { in: CATEGORIES }
  validates :location, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :gears, inclusion: { in: GEARS }
  validates :photo, presence: true
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :bike
  belongs_to :user

  # validates :bike_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :bikes, dependent: :destroy
  has_many :bookings
  has_many :bikes, through: :bookings
  geocoded_by :address
  after_validation :geocode, if: :will_save_change_to_address?

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :address, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def configure_permitted_parameters
    # For additional fields in app/views/devise/registrations/new.html.erb
    devise_parameter_sanitizer.permit(:sign_up, keys: [:first_name, :last_name, :address])

    # For additional in app/views/devise/registrations/edit.html.erb
    devise_parameter_sanitizer.permit(:account_update, keys: [:first_name, :last_name, :address])
  end
end

app/controllers/bikes_controller.rb
class BikesController < ApplicationController
  def index
    @bikes = Bike.where(active: true)
  end

  def near_me
    @bikes = Bike.near(current_user.address, 15)
    @markers = @bikes.geocoded.map do |bike|
      {
        lat: bike.latitude,
        lng: bike.longitude,
        info_window: render_to_string(partial: "info_window", locals: {bike: bike}),
        image_url: helpers.asset_url("freddiefiets.png")
      }
    end
  end

  def new
    @bike = Bike.new
  end

  def categories
    @categories = ['City bike', 'Road bike', 'BMX bike', 'Cargo bike', 'Mountain bike', 'Fixie bike']
  end

  def filter
    @bike_type_query = params[:bike_type]
    @bikes = Bike.where(bike_type: @bike_type_query)
  end

  def show
    @bike = Bike.find(params[:id])
  end

  def create
    @bike = Bike.new(bike_params)
    @bike.user = current_user

    if @bike.save
      redirect_to bike_path(@bike)
    else
      render :new, status: :unprocessable_entity
    end
  end

  def edit
    @bike = Bike.find(params[:id])
  end

  def update
    @bike = Bike.find(params[:id])
    @bike.update(bike_params)
    redirect_to bike_path(@bike)
  end

  def change
    @bike = Bike.find(params[:id])
    @bike.active = !@bike.active
    @bike.save
    redirect_to account_path
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :bike_type, :location, :description, :gears, :photo, :hand_brake, :price, :active)
  end
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  def index
    @myBookings = Booking.where(user: current_user).order(:start_date)
  end

  def new
    if !user_signed_in?
      redirect_to new_user_session_path, notice: "Please, sign in"
    end
    @booking = Booking.new
    @bike = Bike.find(params[:bike_id])
  end

  def create
    @booking = Booking.new(booking_params)
    @booking.user = current_user
    @booking.bike = Bike.find(params[:bike_id])

    # @booking.save!


    if @booking.save!
      redirect_to bookings_path
    end

  end

  private

  def booking_params
    params.require(:booking).permit(:start_date, :end_date)
  end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    @bikes = Bike.all
  end

  def account
    if !user_signed_in?
      redirect_to root_path, notice: "Please, sign in"
    end

    @user_bikes = Bike.where(user: current_user).order(:created_at)
    @user_bookings = Booking.where(user: current_user)
  end

  private

  def bike_params
    params.require(:bike).permit(:name, :bike_type, :location, :description, :gears, :photo, :hand_brake, :price, :active)
  end
end


User.where("name = :name and email = :email", { name: "Joe", email: "joe@example.com" })

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/bikes/_info_window.html.erb
<h2><em><%= bike.name %></em></h2>
<ul>
  <li>Located at: <%= bike.location %></li>
  <li>Price: €<%= bike.price %> per day</li>
  <li>Contact <%= bike.user.first_name %> <%= bike.user.last_name %> if interested</li>
</ul>

app/views/bikes/edit.html.erb
<div class="main-content pt-4 container">

<h1>Bike Editing</h1>

<br>

<%= simple_form_for [@bike] do |f| %>
  <%= f.input :name, label: 'What brand & model is your bike?' %>
  <%= f.input :bike_type, as: :radio_buttons, collection: Bike::CATEGORIES, label: 'What type of bike do you have?' %>
  <%= f.input :location, label: 'What city is your bike in?' %>
  <%= f.input :description, label: 'Provide a brief description of your bike' %>
  <%= f.input :gears, as: :radio_buttons, collection: Bike:: GEARS, label: 'How many gears does your bike have?' %>
  <%= f.input :hand_brakes, as: :boolean, label: 'Tick here if the bike has hand-brakes' %>
  <%= f.input :photo, as: :file, label: 'Upload a photo of your bike' %>
  <%= f.input :price, label: 'How much is a per day rental?' %>
  <%= f.input :active, as: :boolean, label: "Activate or deactivate" %>
  <%= f.submit 'Update your bike', class: 'btn btn-ghost' %>
<% end %>
</div>

app/views/bikes/filter.html.erb
<div class="main-content pt-4 container">

    <h1><%= @bike_type_query %>s</h1>
    <div class="cards">
  <% @bikes.each do |bike| %>
    <%= render "components/cardtrip", bike: bike %>
  <% end %>
  </div>
</div>

app/views/bikes/index.html.erb
<div class="main-content pt-4 container">
  <h1>Bicycles, bicycles, bicycles</h1>
  <%= render "components/buttonfilter"%>
  <div class="cards">
  <% @bikes.each do |bike| %>
    <%= render "components/cardtrip", bike: bike %>
  <% end %>
  </div>
</div>

app/views/bikes/near_me.html.erb
<div class="main-content pt-4 container">
  <h1>Bikes Near Me</h1>
  <div style="width: 100%; height: 350px; margin-bottom: 2rem;"
    data-controller="map"
    data-map-markers-value="<%= @markers.to_json %>"
    data-map-api-key-value="<%= ENV['MAPBOX_API_KEY'] %>">
  </div>
  <div class="cards">
    <% bike_markers = Bike.near(current_user.address, 15)  %>
    <% bike_markers.each do |bike| %>
    <%= render "components/cardtrip", bike: bike %>
    <% end %>
  </div>
</div>

app/views/bikes/new.html.erb
<div class="main-content pt-4 container">

<h1>Bike Listing Creation</h1>

<br>
<%= simple_form_for [@bike] do |f| %>
  <%= f.input :name, label: 'What brand & model is your bike?' %>
  <%= f.input :bike_type, as: :radio_buttons, collection: Bike::CATEGORIES, label: 'What type of bike do you have?' %>
  <%= f.input :location, label: 'What city is your bike in?' %>
  <%= f.input :description, label: 'Provide a brief description of your bike' %>
  <%= f.input :gears, as: :radio_buttons, collection: Bike:: GEARS, label: 'How many gears does your bike have?' %>
  <%= f.input :hand_brakes, as: :boolean, label: 'Tick here if the bike has hand-brakes' %>
  <%= f.input :photo, as: :file, label: 'Upload a photo of your bike' %>
  <%= f.input :price, label: 'How much is a per day rental?' %>
  <%= f.submit 'Create your bike listing', class: 'btn btn-ghost' %>
<% end %>
</div>

app/views/bikes/show.html.erb
<div class="main-content pt-4 container">

  <h1><%= @bike.name %></h1>
  <div class="d-flex">
    <p><i class="fa fa-map-pin" aria-hidden="true"></i>  <%= @bike.location %></p>
  </div>

  <div class="image-card card"> <%# change this so it is smaller reasonable size %>

    <div class="d-flex justify-content-between">
      <%= cl_image_tag(@bike.photo.key) %>
      <div class="bb-card-text align-items-center ">
        <div class="d-flex align-items-right pricing border-bottom">
          <h3> <strong> €<%= @bike.price %> per day </strong></h3>
          <%# <button type="button" class="btn btn-dark"><%= link_to "Back", :back %>
        </div>

        <div class="description">
          <div class="border-bottom">
            <h3><strong><%= @bike.user.first_name.capitalize %>'s </strong><%= @bike.bike_type.downcase %></h3>
          </div>

          <div class="border-bottom">
            <h3>Description:</h3>
            <p><%= @bike.description %></p>
          </div>

          <div class="border-bottom">
            <h3>Bike details:</h3>
            <% if @bike.hand_brakes == true %>
              <p>This bike has hand brakes</p>
            <% else %>
              <p>No hand-brakes</p>
            <% end %>
            <p><%= @bike.gears %> gears</p>
          </div>

          <div>
            <h3>Bike owner:</h3>
            <p><%= @bike.user.first_name %> <%= @bike.user.last_name %></p>
            <%# <p>XX verified</p> %>
          </div>

          <% if current_user == @bike.user %>
            <button type="button" class="btn nodecor btn-ghost"><%= link_to "Edit your bike", edit_bike_path(@bike.id) %></button>
          <% elsif user_signed_in? %>
            <button type="button" class="btn nodecor btn-flat  "><%= link_to "Rent now!", new_bike_booking_path(@bike.id) %></button>
          <% else %>
            <button type="button" class="btn nodecor btn-flat  "><%= link_to "Log in to rent this bike", new_user_session_path %></button>
          <% end %>
        </div>
      </div>

    </div>
  </div>

</div>

  <%# Add logic so possibility of end-date being added %>
  <%# <div class="bb-card-details"> %>
  <%# </div> %>

app/views/bookings/index.html.erb
<div class="main-content pt-4 container">

  <h1 class="fw-bold">Freddie's Fiets Bookings Index</h1>
  <% @myBookings.each do |booking| %>
    <br>
    <h2>Rental information for: <%= link_to booking.bike.name, bike_path(booking.bike) %> (<%= booking.bike.bike_type %>)</h2>
    <p><strong>Renting period: </strong><%= (booking.end_date-booking.start_date).to_i %> days</p>

    <p><strong>Start date: </strong><%= booking.start_date %></p>
    <p><strong>End date: </strong><%= booking.end_date %></p>

    <p><strong>City: </strong> <%= booking.bike.location %></p>
    <p><strong>Total price: </strong> <%= booking.bike.price * (booking.end_date-booking.start_date).to_i %> €</p>
  <% end %>
</div>

app/views/bookings/new.html.erb
<div class="main-content pt-4 container">

  <h1 class="fw-bold">Freddie's Fiets Booking confirmation </h1><br>
  <h4>Hello <%= current_user.first_name %></h4>
  <p>The bike you are requesting is: <%= Bike.find(params[:bike_id]).name %> (<%=Bike.find(params[:bike_id]).bike_type %>)</p><br>


  <%= simple_form_for [@bike, @booking] do |f| %>
  <%= f.input :start_date %>
  <%= f.input :end_date %>
  <%= f.submit class: "btn btn-flat"  %>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Freddie's Fiets</title>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <link href="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.css" rel="stylesheet">
    <meta name="description" content="Don't Stop (Me) Now: Rent a Bike!<br>You want to ride your bicycle, biiicycle, BICYCLE">
    <meta name="keywords" content="Bike, Rent, Le Wagon">
    <meta name="author" content="Adriene, Alvaro, Lucas and Ono (Le Wagon Web Dev 922)">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", defer: true %>
  </head>

  <body>
  <div
    class="page-container"
    data-controller="navbar"
  >

    <div class="navbar-container"> <%# section 1/3 %>
      <%= render "shared/navbar" %>
    </div>
    <div class="content-container"> <%# section 2/3 %>
      <%= yield %>
      <%= render "components/alert" %>
    </div>
    <div class="footer-container"> <%# section 3/3 %>
      <%= render "shared/footer" %>
    </div>
  </div>

    <script src="https://api.mapbox.com/mapbox-gl-js/v2.8.2/mapbox-gl.js"></script>

  </body>
</html>

app/views/pages/account.html.erb
<div class="main-content pt-4 container">
    <h1 class="fw-bold">Freddie's Fiets Dashboard</h1>
  <div class="card bg-light mb-3">
    <div class="card-body ">
      <div class="d-flex justify-content-between">
        <h2 class="fw-bold">User details </h2>
        <%= link_to "Edit your user details", edit_user_registration_path(current_user), class: "btn btn-ghost" %>
      </div>
      <p>First name: <%=current_user.first_name %></p>
      <p>Last name: <%=current_user.last_name %></p>
      <p>E-mail: <%=current_user.email %></p>
    </div>
  </div>

<div class="card bg-light mb-3">
    <div class="card-body ">
      <h2 class="fw-bold">Your bookings</h2>
      <div class="cards">

        <% @user_bookings.each do |user_booking| %>
          <% @content = render "components/card", booking: user_booking %>
          <%= link_to @content, bike_path(user_booking.bike) %>
        <% end %>
      </div>
    </div>
  </div>

  <div class="card bg-light mb-3">
    <div class="card-body ">
      <div class="d-flex justify-content-between">
        <h2 class="fw-bold">Your bikes</h2>
        <%= link_to "List a new bike",  new_bike_path(current_user), class: "btn btn-ghost" %>
      </div>
      <br>
      <% @user_bikes.each do |bike| %>
        <%= render "components/cardproduct", bike: bike %>
      <% end %>
    </div>
  </div>


</div>

app/views/pages/home.html.erb
<%= render "components/banner" %>
<div class="container index">
<%= render "components/buttonfilter"%>
  <h2 class="subheading">Greatests hits</h2>
  <div class="cards">
    <% displayed_bikes = @bikes.sample((6)) %>
    <% displayed_bikes.each do |bike| %>
    <%= render "components/cardtrip", bike: bike %>
    <% end %>
  </div>
</div>

app/views/shared/_footer.html.erb
<div class="footer">
  <div class="footer-links">
    <a href="https://github.com/alvarotrujillo/freddies-fiets" target="_blank"><i class="fab fa-github"></i></a>
    <a href="https://www.instagram.com/explore/tags/fiets/" target="_blank"><i class="fab fa-instagram"></i></a>
    <a href="https://twitter.com/search?q=bikes&src=typed_query" target="_blank"><i class="fab fa-twitter"></i></a>
  </div>
  <div class="authors">
    <h6>Developed on Ruby on Rails by
    <a href="https://github.com/A-drienne" target="_blank">Adrienne</a>,
    <a href="https://github.com/alvarotrujillo" target="_blank">Alvaro</a>,
    <a href="https://github.com/lcalazansl" target="_blank">Lucas</a> &
    <a href="https://github.com/onofrecc" target="_blank">OnO</a>
    </h6>
  </div>
</div>

app/views/shared/_navbar.html.erb
<%# ‼️ Important: This is a static navbar. To enable the login/logout logic in your Rails project,
uncomment the lines of the ERB code which are commented out below. %>

<div
  class="navbar navbar-expand-sm navbar-light navbar-lewagon navbar-transparent"
  data-navbar-target="navbar"
  data-action="scroll@window->navbar#updateNavbar"
>
  <div class="container-fluid">
    <%= link_to root_path,  class: "navbar-brand" do %>
      <%= image_tag "freddiefietstrans.png" %>
    <% end %>

    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>

    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto">
        <% if user_signed_in? %>
          <li class="nav-item active">
            <%= link_to "Bikes", bikes_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Near Me", near_me_path, class: "nav-link" %>
          </li>
          <li class="nav-item active">
            <%= link_to "Bookings", bookings_path(current_user), class: "nav-link" %>
          </li>
            <li class="nav-item active">
            <%= link_to "Dashboard", account_path, class: "nav-link" %>
          </li>
          <li class="nav-item dropdown">
            <%= image_tag "freddie avatar.png", class: "avatar dropdown-toggle", id: "navbarDropdown", data: { bs_toggle: "dropdown" }, 'aria-haspopup': true, 'aria-expanded': false %>
            <div class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
              <%= link_to "List a bike", new_bike_path, class: "dropdown-item" %>
              <%= link_to "Edit profile", edit_user_registration_path, class: "dropdown-item" %>
              <%= link_to "Log out", destroy_user_session_path, class: "dropdown-item", data: {turbo_method: :delete} %>
            </div>
          </li>
        <% else %>
          <li class="nav-item">
            <%= link_to "All bikes", bikes_path, class: "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to "Login", new_user_session_path, class: "nav-link" %>
          </li>
        <% end %>
      </ul>
    </div>
  </div>
</div>